version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: devops_tp
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    networks:
      - devops-network

  app:
    image: php:8.2-apache
    container_name: app-container
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: devops_tp
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - mysql
    networks:
      - devops-network
    ports:
      - "80:80"

networks:
  devops-network:
    driver: bridge

