name: Run PHPUnit Tests

on:
  push:
    branches:
      - test_LigneFacture
  pull_request:
    branches:
      - test_LigneFacture

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'   # Allow root with empty password
          MYSQL_DATABASE: devops_tp
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      CI_ENVIRONMENT: testing
      # Tell CodeIgniter to connect to localhost with no password
      database.default.host: localhost
      database.default.username: root
      database.default.password: ''
      database.default.database: devops_tp
      database.default.DBDriver: MySQLi

    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Install PHP and extensions
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl
          coverage: xdebug

      # 3) Install your project dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev
          composer install --no-interaction

      # 4) Give PHPUnit execution via PHP (bypass chmod)
      - name: Run PHPUnit tests
        run: php ./vendor/bin/phpunit --configuration phpunit.xml.dist