name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: devops_tp  # This will create the database automatically
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      CI_ENVIRONMENT: testing
      ENVIRONMENT: testing
      database.default.host: 127.0.0.1
      database.default.username: root
      database.default.password: ''
      database.default.database: devops_tp
      database.default.DBDriver: MySQLi

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl
          coverage: xdebug

      # Step 3: Install project dependencies via Composer
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev
          composer install --no-interaction

      # Step 4: Wait for MySQL to be ready
      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            mysqladmin ping -h127.0.0.1 --silent && break
            echo 'Waiting for MySQL...'; sleep 5
          done

      # Step 5: Create the necessary tables in the database
      - name: Create test schema
        run: |
          mysql -h127.0.0.1 -u root <<'SQL'
            CREATE DATABASE IF NOT EXISTS devops_tp;
            USE devops_tp;

            -- Creating db_user table with db_ prefix
            CREATE TABLE IF NOT EXISTS db_user (
              id INT AUTO_INCREMENT PRIMARY KEY,
              username VARCHAR(100) NOT NULL,
              email VARCHAR(100) NOT NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

            -- Creating db_lignefacture table with db_ prefix
            CREATE TABLE IF NOT EXISTS db_lignefacture (
              id INT AUTO_INCREMENT PRIMARY KEY,
              idArticle INT DEFAULT NULL,
              Qte INT NOT NULL,
              PU FLOAT NOT NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
          SQL

      # Step 6: Run PHPUnit tests
      - name: Run PHPUnit tests
        run: php ./vendor/bin/phpunit --configuration phpunit.xml.dist
