name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
      - Bon_Livraison_Test
      - add_UserModel_UserController
      - article_test
      - database_update
      - test_LigneFacture
      - test-LigneBonLivraison
      - test-panier
      - tests_table_Facture
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: devops_tp
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, mysqli, pdo_mysql

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for MySQL...";
            sleep 5;
          done

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
        env:
          database.tests.hostname: 127.0.0.1
          database.tests.username: root
          database.tests.password: 
