name: Run PHPUnit Tests

on:
  push:
    branches:
      - test_LigneFacture
  pull_request:
    branches:
      - test_LigneFacture

jobs:
  phpunit:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      # 1) Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up PHP 8.2 with needed extensions and Xdebug for coverage
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl
          coverage: xdebug

      # 3) Install system deps and Composer packages
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev
          composer install --no-interaction

      # 4) Run PHPUnit through PHP (bypassing execute permission issues)
      - name: Run PHPUnit tests
        run: php ./vendor/bin/phpunit --configuration phpunit.xml.dist