name: Run PHPUnit Tests

on:
  push:
    branches: [ test_LigneFacture ]
  pull_request:
    branches: [ test_LigneFacture ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: devops_tp
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      ENVIRONMENT: testing
      CI_ENVIRONMENT: testing
      database.default.host: 127.0.0.1
      database.default.username: root
      database.default.password: ''
      database.default.database: devops_tp
      database.default.DBDriver: MySQLi

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl
          coverage: xdebug

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev
          composer install --no-interaction

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            mysqladmin ping -h127.0.0.1 --silent && break
            echo 'Waiting for MySQL...'; sleep 5
          done

      - name: Run database migrations        # ← NEW STEP
        run: php spark migrate --env testing --quiet

      - name: Run PHPUnit tests
        run: php ./vendor/bin/phpunit --configuration phpunit.xml.dist